"""Freeze compact generated byproduct vectors from the unchanged pinned Python.

The four pure functions are executed on exact f32 mid/side arrays, without file
tools or private audio. --check never overwrites an expected fixture.
"""
import argparse
import json
import math
from pathlib import Path
import numpy as np
from generate_replaygain_reference import ROOT, BASELINE, pinned_function


def samples(case):
    arrays = [np.tile(np.asarray(s["pattern"], dtype=np.float64), (s["repeat"], 1)) for s in case["segments"]]
    return np.concatenate(arrays) if arrays else np.empty((0, case["channels"]))


def cases():
    out = []
    def add(name, pattern, count, rate=8000, extra=None, prefix=None):
        segs = [{"pattern": pattern, "repeat": count}]
        segs += extra or []
        out.append(dict(name=name, channels=len(pattern[0]), rate=rate, segments=segs, prefix_frames=prefix))
    def seg(pattern, repeat):
        return {"pattern": pattern, "repeat": repeat}
    add("silence", [[0, 0]], 8000)
    add("dc", [[.25, -.125]], 8000)
    add("mono_sine_equivalent", [[.5], [-.5]], 4000)
    add("dual_mono", [[.5, .5], [-.5, -.5]], 4000)
    add("antiphase", [[.5, -.5], [-.5, .5]], 4000)
    add("unequal_gain_dc", [[.75, .125], [-.25, -.375]], 4000)
    add("uncorrelated", [[.5, .5], [.5, -.5], [-.5, .5], [-.5, -.5]], 2000)
    add("mean_blocks_not_whole", [[.5, .5], [-.5, -.5]], 400,
        extra=[seg([[.03125, -.03125], [-.03125, .03125]], 400)])
    add("silent_window_and_tail", [[0, 0]], 800,
        extra=[seg([[.25, .25], [-.25, -.25]], 400), seg([[.5, -.5]], 799)])
    for n in (0, 9, 10, 1000):
        add(f"ceiling_{n}", [[0, 0]], 8000 - n, extra=[seg([[1 - 1/32768, 0]], n)])
    add("plateau_below_ceiling", [[.9, -.9]], 8000)
    add("overrange_float", [[1.25, -1.5], [-1.25, 1.5]], 4000)
    add("precision24_fixed_ceiling", [[1 - 1/32768, -1 + 1/32768]], 8000)
    add("quiet_just_short", [[0]], 3999, extra=[seg([[.25]], 4001)])
    add("quiet_half_second", [[0]], 4000, extra=[seg([[.25]], 4000)])
    add("quiet_trailing_equality", [[.25]], 4000, extra=[seg([[0]], 4000)])
    threshold = float(np.float32(.001))
    add("silence_strict_equality", [[threshold]], 8000)
    add("silence_below_threshold", [[float(np.nextafter(np.float32(.001), np.float32(0)))]], 8000)
    add("fade", [[.25]], 2000, extra=[seg([[.005]], 2000), seg([[.0005]], 2000), seg([[0]], 2000)])
    add("noise_positive_p5", [[0]], 800,
        extra=[seg([[v], [-v]], 400) for v in (.5, .25, .125, .0625, .03125, .015625, .0078125, .00390625, .001953125)])
    add("noise_four_positive", [[0]], 4800, extra=[seg([[.125]], 3200)])
    add("noise_short", [[.125]], 7999)
    add("phase_short", [[.125, .125]], 799)
    add("phase_variance_below_gate", [[1e-8, 1e-8], [-1e-8, -1e-8]], 4000)
    add("phase_variance_above_gate", [[1e-7, 1e-7], [-1e-7, -1e-7]], 4000)
    add("prefix_percent", [[0]], 4000, extra=[seg([[.25]], 12000)], prefix=8000)
    add("odd_rate_half_second", [[0]], 5512, rate=11025, extra=[seg([[.25]], 5513)])
    add("reconstruction_rounding", [[.99999994, .33333334], [-.12500001, .5]], 4000)
    return out


def expected(case, functions):
    deck = samples(case)
    if case["prefix_frames"] is not None:
        deck = deck[:case["prefix_frames"]]
    f32 = deck.astype(np.float32)
    mid = f32[:, 0] if case["channels"] == 1 else (f32[:, 0] + f32[:, 1]) / np.float32(2)
    side = None if case["channels"] == 1 else (f32[:, 0] - f32[:, 1]) / np.float32(2)
    phase, clip, floor, silence = functions
    rate, n = case["rate"], len(mid)
    # D02: oracle observes the analyzed duration, not the declared full duration.
    pct, sections = silence(mid, rate, n / rate)
    block = rate // 10
    blocks = n // block
    rms = np.sqrt(np.mean(mid[:blocks * block].reshape(blocks, block).astype(np.float64) ** 2, axis=1))
    positive = rms[rms > 0]
    p5 = float(np.percentile(positive, 5)) if n >= rate and len(positive) >= 5 else None
    valid = 0
    correlation = None
    if side is not None and blocks:
        left = (mid[:blocks*block] + side[:blocks*block]).reshape(blocks, block).astype(np.float64)
        right = (mid[:blocks*block] - side[:blocks*block]).reshape(blocks, block).astype(np.float64)
        left -= left.mean(axis=1, keepdims=True)
        right -= right.mean(axis=1, keepdims=True)
        denom = np.sqrt(np.sum(left*left, axis=1)*np.sum(right*right, axis=1))
        mask = denom > 1e-12
        valid = int(mask.sum())
        if valid:
            correlation = float(np.mean((np.sum(left*right, axis=1)/np.where(mask, denom, 1))[mask]))
    quiet = np.abs(mid) < 10 ** (-60/20)
    d = np.diff(np.concatenate(([False], quiet, [False])).astype(np.int8))
    runs = [[int(s), int(e)] for s, e in zip(np.where(d == 1)[0], np.where(d == -1)[0]) if e-s >= int(.5*rate)]
    return dict(frames=n, phase=list(phase(mid, side, rate)), correlation=correlation, valid_blocks=valid,
                clipping=list(clip(mid, side)), floor=floor(mid, rate), percentile_rms=p5,
                positive_blocks=len(positive), silence_pct=pct, sections=sections, runs=runs)


def fixture():
    namespace = {"np": np, "math": math, "_NUMPY_OK": True}
    functions = [pinned_function(name, namespace) for name in
                 ("measure_phase_correlation", "detect_clipping", "_noise_floor_from_audio", "map_silence")]
    vectors = cases()
    for case in vectors:
        case["expected"] = expected(case, functions)
    return dict(reference_commit=BASELINE, oracle="pinned pure functions + independent dense NumPy counts/numerics on f32 mono/mid/side; D02 analyzed denominator",
                cases=vectors)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=ROOT / "tests/fixtures/byproduct_reference.json")
    args = parser.parse_args()
    data = json.dumps(fixture(), ensure_ascii=False, indent=2, allow_nan=False) + "\n"
    if args.check:
        assert args.output.read_text(encoding="utf-8") == data, "frozen byproduct fixture drift"
    else:
        with args.output.open("x", encoding="utf-8") as out:
            out.write(data)
    print(f"PASS: {len(cases())} generated pinned byproduct vectors; {'unchanged' if args.check else 'frozen'}")


if __name__ == "__main__":
    main()
